- hosts: 172.25.4.131
  user: root
  tasks:
    - name: mkdir /demosite
      file: path=/demosite state=directory
    - name: mkdir /website
      file: path=/website state=directory
    - name: copy wsgi.py
      copy: src=/mnt/test-obj-online/wsgi.py dest=/demosite/wsgi.py
    - name: uwsgi
      shell: uwsgi --ini /etc/uwsgi9090.ini
